use std::fmt;

use base64::{Engine as _, engine::general_purpose::URL_SAFE_NO_PAD};
use bondry_core::PrincipalId;
use sha2::{Digest, Sha256};
use subtle::ConstantTimeEq;
use thiserror::Error;
use zeroize::Zeroizing;

const TOKEN_FORMAT: &str = "bondry_v1";
const TOKEN_ID_PREFIX: &str = "token_";
const TOKEN_ID_RANDOM_BYTES: usize = 16;
const TOKEN_SECRET_BYTES: usize = 32;
const MAX_TOKEN_LABEL_LENGTH: usize = 128;

/// A validated public identifier for an access token.
#[derive(Clone, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct TokenId(String);

impl TokenId {
    /// Parses a token identifier generated by Bondry.
    pub fn new(value: impl Into<String>) -> Result<Self, TokenIdError> {
        let value = value.into();
        let encoded = value
            .strip_prefix(TOKEN_ID_PREFIX)
            .ok_or(TokenIdError::Invalid)?;
        let bytes = URL_SAFE_NO_PAD
            .decode(encoded)
            .map_err(|_| TokenIdError::Invalid)?;
        if bytes.len() != TOKEN_ID_RANDOM_BYTES {
            return Err(TokenIdError::Invalid);
        }
        Ok(Self(value))
    }

    /// Returns the token identifier.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }

    fn from_random_bytes(bytes: &[u8; TOKEN_ID_RANDOM_BYTES]) -> Result<Self, TokenIdError> {
        Self::new(format!(
            "{TOKEN_ID_PREFIX}{}",
            URL_SAFE_NO_PAD.encode(bytes)
        ))
    }
}

/// An invalid token identifier.
#[derive(Clone, Copy, Debug, Eq, Error, PartialEq)]
pub enum TokenIdError {
    /// The identifier is not a canonical Bondry token identifier.
    #[error("invalid token identifier")]
    Invalid,
}

/// An optional administrative label for a token.
#[derive(Clone, Debug, Eq, Hash, PartialEq)]
pub struct TokenLabel(String);

impl TokenLabel {
    /// Creates a trimmed, non-empty token label.
    pub fn new(value: impl Into<String>) -> Result<Self, TokenLabelError> {
        let value = value.into();
        let value = value.trim();
        if value.is_empty() {
            return Err(TokenLabelError::Empty);
        }
        if value.len() > MAX_TOKEN_LABEL_LENGTH {
            return Err(TokenLabelError::TooLong);
        }
        Ok(Self(value.to_owned()))
    }

    /// Returns the administrative label.
    #[must_use]
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

/// An invalid token label.
#[derive(Clone, Copy, Debug, Eq, Error, PartialEq)]
pub enum TokenLabelError {
    /// The label is empty after trimming.
    #[error("a token label cannot be empty")]
    Empty,
    /// The label exceeds the supported encoded length.
    #[error("a token label cannot exceed {MAX_TOKEN_LABEL_LENGTH} bytes")]
    TooLong,
}

/// A SHA-256 digest of a 256-bit random token secret.
#[derive(Clone, Eq, PartialEq)]
pub struct TokenDigest([u8; 32]);

impl TokenDigest {
    /// Reconstructs a digest from trusted persistent state.
    #[must_use]
    pub const fn from_bytes(bytes: [u8; 32]) -> Self {
        Self(bytes)
    }

    /// Returns the digest bytes for persistence.
    #[must_use]
    pub const fn as_bytes(&self) -> &[u8; 32] {
        &self.0
    }

    fn from_secret(secret: &[u8]) -> Self {
        Self(Sha256::digest(secret).into())
    }

    fn matches(&self, candidate: &Self) -> bool {
        bool::from(self.0.ct_eq(&candidate.0))
    }
}

impl fmt::Debug for TokenDigest {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("TokenDigest([REDACTED])")
    }
}

/// A stored token record that never contains the presented secret.
#[derive(Clone, Eq, PartialEq)]
pub struct TokenRecord {
    id: TokenId,
    client: PrincipalId,
    label: Option<TokenLabel>,
    digest: TokenDigest,
    created_at_unix_seconds: i64,
    expires_at_unix_seconds: Option<i64>,
    revoked_at_unix_seconds: Option<i64>,
}

impl TokenRecord {
    /// Reconstructs a token from trusted persistent state.
    #[must_use]
    pub const fn from_stored_parts(
        id: TokenId,
        client: PrincipalId,
        label: Option<TokenLabel>,
        digest: TokenDigest,
        created_at_unix_seconds: i64,
        expires_at_unix_seconds: Option<i64>,
        revoked_at_unix_seconds: Option<i64>,
    ) -> Self {
        Self {
            id,
            client,
            label,
            digest,
            created_at_unix_seconds,
            expires_at_unix_seconds,
            revoked_at_unix_seconds,
        }
    }

    /// Returns the token identifier.
    #[must_use]
    pub const fn id(&self) -> &TokenId {
        &self.id
    }

    /// Returns the owning client principal.
    #[must_use]
    pub const fn client(&self) -> &PrincipalId {
        &self.client
    }

    /// Returns the optional administrative label.
    #[must_use]
    pub const fn label(&self) -> Option<&TokenLabel> {
        self.label.as_ref()
    }

    /// Returns the stored secret digest.
    #[must_use]
    pub const fn digest(&self) -> &TokenDigest {
        &self.digest
    }

    /// Returns the creation time as Unix seconds.
    #[must_use]
    pub const fn created_at_unix_seconds(&self) -> i64 {
        self.created_at_unix_seconds
    }

    /// Returns the optional expiration time as Unix seconds.
    #[must_use]
    pub const fn expires_at_unix_seconds(&self) -> Option<i64> {
        self.expires_at_unix_seconds
    }

    /// Returns the optional revocation time as Unix seconds.
    #[must_use]
    pub const fn revoked_at_unix_seconds(&self) -> Option<i64> {
        self.revoked_at_unix_seconds
    }

    /// Marks the stored record as revoked at the given Unix time.
    pub fn mark_revoked(&mut self, revoked_at_unix_seconds: i64) {
        self.revoked_at_unix_seconds = Some(revoked_at_unix_seconds);
    }

    /// Returns whether the token is neither revoked nor expired.
    #[must_use]
    pub fn is_active_at(&self, unix_seconds: i64) -> bool {
        self.revoked_at_unix_seconds.is_none()
            && self
                .expires_at_unix_seconds
                .is_none_or(|expires_at| unix_seconds < expires_at)
    }

    /// Returns a copy of the non-secret administrative metadata.
    #[must_use]
    pub fn metadata(&self) -> TokenMetadata {
        TokenMetadata {
            id: self.id.clone(),
            client: self.client.clone(),
            label: self.label.clone(),
            created_at_unix_seconds: self.created_at_unix_seconds,
            expires_at_unix_seconds: self.expires_at_unix_seconds,
            revoked_at_unix_seconds: self.revoked_at_unix_seconds,
        }
    }
}

impl fmt::Debug for TokenRecord {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("TokenRecord")
            .field("id", &self.id)
            .field("client", &self.client)
            .field("label", &self.label)
            .field("digest", &"[REDACTED]")
            .field("created_at_unix_seconds", &self.created_at_unix_seconds)
            .field("expires_at_unix_seconds", &self.expires_at_unix_seconds)
            .field("revoked_at_unix_seconds", &self.revoked_at_unix_seconds)
            .finish()
    }
}

/// Non-secret token state suitable for an administrative interface.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TokenMetadata {
    id: TokenId,
    client: PrincipalId,
    label: Option<TokenLabel>,
    created_at_unix_seconds: i64,
    expires_at_unix_seconds: Option<i64>,
    revoked_at_unix_seconds: Option<i64>,
}

impl TokenMetadata {
    /// Reconstructs non-secret metadata from trusted persistent state.
    #[must_use]
    pub const fn from_stored_parts(
        id: TokenId,
        client: PrincipalId,
        label: Option<TokenLabel>,
        created_at_unix_seconds: i64,
        expires_at_unix_seconds: Option<i64>,
        revoked_at_unix_seconds: Option<i64>,
    ) -> Self {
        Self {
            id,
            client,
            label,
            created_at_unix_seconds,
            expires_at_unix_seconds,
            revoked_at_unix_seconds,
        }
    }

    /// Returns the token identifier.
    #[must_use]
    pub const fn id(&self) -> &TokenId {
        &self.id
    }

    /// Returns the owning client principal.
    #[must_use]
    pub const fn client(&self) -> &PrincipalId {
        &self.client
    }

    /// Returns the optional administrative label.
    #[must_use]
    pub const fn label(&self) -> Option<&TokenLabel> {
        self.label.as_ref()
    }

    /// Returns the creation time as Unix seconds.
    #[must_use]
    pub const fn created_at_unix_seconds(&self) -> i64 {
        self.created_at_unix_seconds
    }

    /// Returns the optional expiration time as Unix seconds.
    #[must_use]
    pub const fn expires_at_unix_seconds(&self) -> Option<i64> {
        self.expires_at_unix_seconds
    }

    /// Returns the optional revocation time as Unix seconds.
    #[must_use]
    pub const fn revoked_at_unix_seconds(&self) -> Option<i64> {
        self.revoked_at_unix_seconds
    }
}

/// A newly issued token secret that is redacted from debug output and zeroized on drop.
pub struct SecretToken {
    value: Zeroizing<String>,
}

impl SecretToken {
    /// Exposes the token for the deliberate act of copying it to a client.
    #[must_use]
    pub fn expose(&self) -> &str {
        self.value.as_str()
    }
}

impl fmt::Debug for SecretToken {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("SecretToken([REDACTED])")
    }
}

/// A token returned once at issuance or rotation time.
pub struct IssuedToken {
    metadata: TokenMetadata,
    secret: SecretToken,
}

impl IssuedToken {
    pub(crate) const fn new(metadata: TokenMetadata, secret: SecretToken) -> Self {
        Self { metadata, secret }
    }

    /// Returns the non-secret token metadata.
    #[must_use]
    pub const fn metadata(&self) -> &TokenMetadata {
        &self.metadata
    }

    /// Returns the one-time token secret.
    #[must_use]
    pub const fn secret(&self) -> &SecretToken {
        &self.secret
    }
}

pub(crate) trait RandomSource: Send + Sync {
    fn fill(&self, destination: &mut [u8]) -> Result<(), RandomError>;
}

pub(crate) struct SystemRandom;

impl RandomSource for SystemRandom {
    fn fill(&self, destination: &mut [u8]) -> Result<(), RandomError> {
        getrandom::fill(destination).map_err(|_| RandomError)
    }
}

pub(crate) struct RandomError;

pub(crate) struct GeneratedToken {
    pub(crate) id: TokenId,
    pub(crate) digest: TokenDigest,
    pub(crate) secret: SecretToken,
}

impl GeneratedToken {
    pub(crate) fn generate(random: &dyn RandomSource) -> Result<Self, RandomError> {
        let mut id_bytes = [0_u8; TOKEN_ID_RANDOM_BYTES];
        let mut secret_bytes = Zeroizing::new([0_u8; TOKEN_SECRET_BYTES]);
        random.fill(&mut id_bytes)?;
        random.fill(secret_bytes.as_mut())?;

        let id = TokenId::from_random_bytes(&id_bytes).map_err(|_| RandomError)?;
        let digest = TokenDigest::from_secret(secret_bytes.as_ref());
        let encoded_secret = Zeroizing::new(URL_SAFE_NO_PAD.encode(secret_bytes.as_ref()));
        let value = Zeroizing::new(format!(
            "{TOKEN_FORMAT}.{}.{}",
            id.as_str(),
            encoded_secret.as_str()
        ));
        Ok(Self {
            id,
            digest,
            secret: SecretToken { value },
        })
    }
}

pub(crate) struct PresentedToken {
    pub(crate) id: TokenId,
    pub(crate) digest: TokenDigest,
}

impl PresentedToken {
    pub(crate) fn parse(value: &str) -> Result<Self, ()> {
        let mut parts = value.split('.');
        let format = parts.next().ok_or(())?;
        let id = parts.next().ok_or(())?;
        let encoded_secret = parts.next().ok_or(())?;
        if parts.next().is_some() || format != TOKEN_FORMAT {
            return Err(());
        }

        let id = TokenId::new(id).map_err(|_| ())?;
        let secret = Zeroizing::new(URL_SAFE_NO_PAD.decode(encoded_secret).map_err(|_| ())?);
        if secret.len() != TOKEN_SECRET_BYTES {
            return Err(());
        }
        Ok(Self {
            id,
            digest: TokenDigest::from_secret(secret.as_ref()),
        })
    }

    pub(crate) fn matches(&self, stored: &TokenDigest) -> bool {
        stored.matches(&self.digest)
    }
}

#[cfg(test)]
mod tests {
    use base64::{Engine as _, engine::general_purpose::URL_SAFE_NO_PAD};

    use super::{
        GeneratedToken, PresentedToken, RandomError, RandomSource, TokenDigest, TokenId,
        TokenIdError, TokenLabel, TokenLabelError,
    };

    struct FixedRandom(u8);

    impl RandomSource for FixedRandom {
        fn fill(&self, destination: &mut [u8]) -> Result<(), RandomError> {
            destination.fill(self.0);
            Ok(())
        }
    }

    #[test]
    fn generated_tokens_parse_and_match_their_digest() -> Result<(), Box<dyn std::error::Error>> {
        let generated = GeneratedToken::generate(&FixedRandom(7))
            .map_err(|_| std::io::Error::other("deterministic generation unexpectedly failed"))?;
        let presented = PresentedToken::parse(generated.secret.expose())
            .map_err(|()| std::io::Error::other("generated token did not parse"))?;

        assert_eq!(presented.id, generated.id);
        assert!(presented.matches(&generated.digest));
        assert_eq!(format!("{:?}", generated.digest), "TokenDigest([REDACTED])");
        Ok(())
    }

    #[test]
    fn token_identifiers_are_strict_and_canonical() -> Result<(), TokenIdError> {
        let encoded = URL_SAFE_NO_PAD.encode([0_u8; 16]);
        let id = TokenId::new(format!("token_{encoded}"))?;
        assert!(id.as_str().starts_with("token_"));

        for invalid in ["", "token_", "client_AAAAAAAAAAAAAAAAAAAAAA", "token_***"] {
            assert_eq!(TokenId::new(invalid), Err(TokenIdError::Invalid));
        }
        Ok(())
    }

    #[test]
    fn presented_tokens_reject_noncanonical_shapes() {
        let id = format!("token_{}", URL_SAFE_NO_PAD.encode([0_u8; 16]));
        let secret = URL_SAFE_NO_PAD.encode([0_u8; 32]);
        for invalid in [
            format!("bondry_v2.{id}.{secret}"),
            format!("bondry_v1.{id}.{secret}.extra"),
            format!("bondry_v1.{id}.short"),
            format!("bondry_v1.invalid.{secret}"),
        ] {
            assert!(PresentedToken::parse(&invalid).is_err());
        }
    }

    #[test]
    fn token_labels_are_trimmed_and_bounded() -> Result<(), TokenLabelError> {
        assert_eq!(TokenLabel::new("  Primary  ")?.as_str(), "Primary");
        assert_eq!(TokenLabel::new(" \n "), Err(TokenLabelError::Empty));
        assert_eq!(
            TokenLabel::new("é".repeat(65)),
            Err(TokenLabelError::TooLong)
        );
        Ok(())
    }

    #[test]
    fn digest_comparison_rejects_different_values() {
        let first = TokenDigest::from_bytes([1_u8; 32]);
        let second = TokenDigest::from_bytes([2_u8; 32]);
        assert!(first.matches(&first));
        assert!(!first.matches(&second));
    }
}
