#![doc = "Versioned C ABI for Bondry egress."]

mod config;
mod ffi;
mod secrets;
mod store;
mod transport;

pub use secrets::{
    BONDRY_SECRET_PROVIDER_ABI_VERSION_V1, BondrySecretProviderV1, BondrySecretResolutionV1,
    BondrySecretResolveV1,
};
pub use transport::{
    BONDRY_CONNECTION_EVIDENCE_CLEARTEXT_V1, BONDRY_CONNECTION_EVIDENCE_MISSING_V1,
    BONDRY_CONNECTION_EVIDENCE_TLS_V1, BONDRY_HTTP_RESULT_ERROR_V1, BONDRY_HTTP_RESULT_RESPONSE_V1,
    BONDRY_HTTP_TRANSPORT_ABI_VERSION_V1, BONDRY_IP_ADDRESS_V4_V1, BONDRY_IP_ADDRESS_V6_V1,
    BONDRY_TRANSPORT_ERROR_CLEARTEXT_DENIED_V1, BONDRY_TRANSPORT_ERROR_CONNECTION_FAILED_V1,
    BONDRY_TRANSPORT_ERROR_DEADLINE_EXCEEDED_V1, BONDRY_TRANSPORT_ERROR_EVIDENCE_MISMATCH_V1,
    BONDRY_TRANSPORT_ERROR_INVALID_LIMITS_V1, BONDRY_TRANSPORT_ERROR_INVALID_MESSAGE_V1,
    BONDRY_TRANSPORT_ERROR_INVALID_RESPONSE_V1,
    BONDRY_TRANSPORT_ERROR_LINK_LOCAL_CLEARTEXT_DENIED_V1,
    BONDRY_TRANSPORT_ERROR_LINK_LOCAL_SCOPE_REQUIRED_V1,
    BONDRY_TRANSPORT_ERROR_LOOPBACK_INTENT_REQUIRED_V1, BONDRY_TRANSPORT_ERROR_MISSING_EVIDENCE_V1,
    BONDRY_TRANSPORT_ERROR_PRIVATE_CLEARTEXT_DENIED_V1, BONDRY_TRANSPORT_ERROR_REDIRECT_DENIED_V1,
    BONDRY_TRANSPORT_ERROR_REQUEST_TOO_LARGE_V1, BONDRY_TRANSPORT_ERROR_RESPONSE_TOO_LARGE_V1,
    BONDRY_TRANSPORT_ERROR_TLS_FAILED_V1, BONDRY_TRANSPORT_ERROR_TLS_IDENTITY_MISMATCH_V1,
    BONDRY_TRANSPORT_ERROR_UNSUPPORTED_ENDPOINT_V1, BondryByteSliceV1, BondryConnectionEvidenceV1,
    BondryContextReleaseV1, BondryContextRetainV1, BondryEndpointPolicyV1, BondryHTTPCompletionV1,
    BondryHTTPHeaderV1, BondryHTTPRequestV1, BondryHTTPResultV1, BondryHTTPSendV1,
    BondryHTTPTransportV1,
};

/// The first Bondry egress C ABI version.
pub const BONDRY_EGRESS_ABI_VERSION_V1: u32 = 1;

#[cfg(test)]
#[used]
static LINK_RUNTIME_FFI: extern "C" fn() -> u32 = bondry_runtime_ffi::bondry_abi_version_v1;

/// Returns the egress ABI version implemented by the linked library.
#[must_use]
#[unsafe(no_mangle)]
pub extern "C" fn bondry_egress_abi_version_v1() -> u32 {
    BONDRY_EGRESS_ABI_VERSION_V1
}
pub use ffi::*;
